### ISSUE TITLE
Adjusting the filter for model.annotate(stream)

### ISSUE THREAD

**Issue by maritinkolej** [seisbench/seisbench#121]
How do I adjust the filter when I run the model.annotate (stream) because I am working with 20 Hz and 40 Hz sampled data. The warning message is given below
/home/bgi/.local/lib/python3.8/site-packages/obspy/signal/filter.py:63: UserWarning: Selected high corner frequency (45) of bandpass is at or above Nyquist (20.0). Applying a high-pass instead.

Also where can I find the additional annotate optional arguments??

**Comment by yetinam** [comment]
Hey Martin,

the filters can be adjusted by overwriting the `filter_args` and `filter_kwargs` properties of the model object after loading weights. These are directly passed to the filter function (`stream.filter(*filter_args, **filter_kwargs)`).

Regarding your second question, unfortunately the additional arguments are so far poorly documented. It's already tracked as #100, but I fear it will take a bit until we get to it.

**Comment by maritinkolej** [comment]
Thank you

**Comment by maritinkolej** [comment]
Hello.
I am trying to overwrite the filter_args and filter_kwargs properties of the model object.

pn_preds = pn_model.annotate(stream)
eqt_preds = eqt_model.annotate(stream)
gpd_preds = gpd_model.annotate(stream)
filter_args = dict(sampling_rate=20)
filter_kwargs = dict(sampling_rate=20)
stream.filter(*filter_args, **filter_kwargs)

pn_preds

I am not sure if I am doing the right thing. 
I am using a dataset sampled at 20 Hz. The error keeps coming. /home/bgi/.local/lib/python3.8/site-packages/obspy/signal/filter.py:63: UserWarning: Selected high corner frequency (45) of bandpass is at or above Nyquist (20.0). Applying a high-pass instead.

**Comment by yetinam** [comment]
Hi @maritinkolej ,

thanks for your question. With your current code, you filter the stream **after** applying the models, i.e., the statement has no effect. If you want to manually filter your stream, just put the `stream.filter` statement first. Note however that your `filter_args` and `filter_kwargs` are invalid. Check the [obspy documentation](https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.filter.html) for details on how to use the filter.

For automatically performing the filtering you need to overwrite the `filter_args` and `filter_kwargs` variables of the models.

The warning just tells you that it does not have any effect to filter a trace with a 20 Hz Nyqist frequency (40 Hz sampling rate) at 45 Hz because anyhow no frequencies above this value can be represented.

**Comment by maritinkolej** [comment]
Thank you for the detailed answer. It is easier to overwrite the filter_args and filter_kwargs variables of the models.
Thanks again
