### ISSUE TITLE
How to calcuate the amplitude of those picked phases

### ISSUE THREAD

**Issue by EmiyaT** [seisbench/seisbench#125]
Hi @yetinam 

After studying Seisbench's documents，I started using Seisbench and Gamma to build a earthquake catalog. The convenient of Seisbench makes it really easy to make an accurate catalog with time and location. **However**,my work also needs magnitudes of these events in the catalog for further study and I fail to manage it. It seems that picks with default parameters don't record amplitude information. I am sorry to bother you but could you possibly tell me what I can do to get the amplitude of picks?

Thank you very much

**Comment by yetinam** [comment]
Hi @EmiyaT,

thank you for your interest in SeisBench. Indeed, the picks in SeisBench do not record the actual amplitude of the trace. The reason is, that this requires knowledge of the instrument response and that determining the amplitude implies some choice, e.g., the window in which to look for the peak amplitude. However, you can determine amplitudes by hand with the following steps:

- Remove the instrument response (or at least instrument sensitivity) from the trace. You will need a station inventory for this.
- For each pick, select a window around the pick (usually mostly after) and determine the amplitue.

Here's an example code I used in another project. For stability reasons, I'm using half of the peak to peak amplitude as the measure.

```python
def get_pick_amplitude(pick, stream, window=(-1, 5)):
    trace = stream.select(id=f"{pick.trace_id}.HHZ").slice(
        pick.peak_time + window[0], pick.peak_time + window[1]
    )
    trace = trace[0]
    amp = trace.data.max() - trace.data.min()
    return amp
```

**Comment by EmiyaT** [comment]
Thanks for your quick response!
