### ISSUE TITLE
Question about applying filters

### ISSUE THREAD

**Issue by javak87** [seisbench/seisbench#140]
Dear seisbench developers,
I want to apply "bandpass" filter for all channel of my data. I used the augmentation as follows:

sbg.WindowAroundSample(list(phase_dict.keys()), samples_before=3000, windowlen=4000, selection="random", strategy="variable"),
sbg.RandomWindow(windowlen=3001, strategy="pad"),
sbg.Normalize(demean_axis=-1, amp_norm_axis=-1, amp_norm_type="std"),
sbg.ChangeDtype(np.float32),
sbg.Filter(N=3,Wn=np.array([2., 25.], dtype=np.float32), btype='bandpass')

The problem is that I don't understand what is the "Filter order". I just leave it N=3.
When I use the this filter, the following error comes up:

Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

I'm using the same Wn data type and stream data, but this error comes up.
Could you please help me to revise this line to get ride of this error?
Best regards,
Javad

**Comment by yetinam** [comment]
Hi @javak87,

the issue is that `sbg.Filter` internally relies on `scipy.filter` which always outputs float64 values (DoubleTensor), while the model expects float32 (FloatTensor). Just swap the last two augmentations and you should be good. Let me know if that solves your issue (and close that issue in that case) or if you have any further questions.

**Comment by javak87** [comment]
Dear yetinam,
Thank you for your response. The problem was solved.
Best regards,
Javad
