### ISSUE TITLE
The length of output trace is shorter than the length of input trace in GPD and EQT

### ISSUE THREAD

**Issue by daihz** [seisbench/seisbench#143]
Hi, when I ran the example in 

> ./examples/02a_deploy_model_on_streams_example.ipynb

I found that the length of output trace is shorter than the length of trace which in the input stream.
And the time of output trace is different from input trace. This seems to occur only in GPD and EQT model.
I would like to know why? Thanks.
The stream in the figure is input stream.

![屏幕截图(5)](https://user-images.githubusercontent.com/111106962/201910554-d61ae020-e38d-4475-97aa-5fdda0eea255.png)

**Comment by yetinam** [comment]
Hi @daihz,

the different trace length of input and output have different reasons for GPD and EQTransformer.

- For GPD the different length comes from the fact that GPD always only provides predictions for one point. Therefore we use it in sliding mode with a given stride. By default the stride is 10, leading to a 10x reduction in samples. In addition, this mode does not allow to annotate the first and last 2 s of the trace, leading to a few further missing samples.
- For EQTransformer, the earliest and last prediction samples have proven unreliable due to border effects. We therefore blind them. This leads to missing output samples for the very start and end. Try running `eqt_model.annotate(stream, blinding=(0, 0))`. This should lead to no missing samples.

I hope this answers your question. Feel free to reopen the issue if you have further questions.
