### ISSUE TITLE
 "03b_creating_a_dataset.ipynb" adds traces for both P and S individually (not in one trace)

### ISSUE THREAD

**Issue by javak87** [seisbench/seisbench#164]
Dear @yetinam,
I'm going to use EQT for transfer learning with our own catalog. I looked at the following seisbench documentation:
https://github.com/seisbench/seisbench/blob/main/examples/03b_creating_a_dataset.ipynb

According to this documentation, I created a dataset containing metadata and hdf files. To train EQT, you should have both phases in metadata in one row. However, when I looked at the output of metadata, I realized that for each pick, one row in metadata is created. If we feed this data into EQT, it will learn in the wrong way. For example, if we have both two phases in one station and the distance between P pick and S pick is 5 seconds, both phases should appear in one row in metadata.
You can look at the generated metadata for our catalog as following
[metadata.csv](https://github.com/seisbench/seisbench/files/10420369/metadata.csv)

I used 100 Hz sampling rate and set "time_before=60", "time_after=60"
Could you please tell me how can i fix this problem?
Thanks

**Comment by yetinam** [comment]
Dear @javak87 ,

indeed, tutorial 03b writes one row for each pick. This is not a good strategy for training, as indicated at the bottom of this notebook. Please follow [the link](https://github.com/seisbench/seisbench/blob/df94dcd86ce66d6a2ee2bd00da3857259fe579bd/seisbench/data/ethz.py#L109) provided there for an example on how to group picks. In general, you'll need to update the functions used to create the metadata to put multiple picks into the metadata dictionary before passing it to `writer.add_trace`.

We originally built the tutorial with picks in separate lines for simplicity but turns out it's not really didactic this way. There are a few planned changes, including adding the grouping of picks to the example, tracked in #153. I'm closing this issue in favor of #153.

**Comment by javak87** [comment]
Dear @yetinam,
Thank you for your great support.
