### ISSUE TITLE
Probelm with event index

### ISSUE THREAD

**Issue by javak87** [seisbench/seisbench#215]
Dear Jannes,
First of thank you for your great package.
I saw an issue related to the event index after association with gamma.
The problem is the picks that are associated are correct, but the assigned event is not correct. I think the the problem belongs to event index.  Here is :
event_time : 2011-01-01T03:47:04.963
Pick time related to this event is UTCDateTime(2011, 1, 1, 11, 51, 36, 138393) which is not correct.
Could you please check the event index?
Thanks

**Comment by yetinam** [comment]
Hi @javak87 ,

thanks for your question. I'm not sure I fully understand the problem. My suspicion is that your issue comes from the difference between the event index and the index of the row within the event dataframe, i.e., `catalog.iloc[idx]` might give you an event that has an `event_index` different from `idx`. Therefore, you should always use the `event_index` column of the output. This column corresponds to the `event_index` column in the `assignments`.

Please note that GaMMA is not part of SeisBench. Please raise questions about GaMMA on [their issue page](https://github.com/AI4EPS/GaMMA/issues).

Does this answer your question?

**Comment by yetinam** [comment]
Closing the issue as inactive. Feel free to reopen if the issue persists.
