### ISSUE TITLE
Dataset not in Seisbench Repository

### ISSUE THREAD

**Issue by MarcoEsposito890** [seisbench/seisbench#224]
Hello,

I encounter this Warning when downloading the ETHZ or STEAD datasets.

Dataset ETHZ not in SeisBench repository. Starting download and conversion from source.
WARNING:seisbench:Dataset ETHZ not in SeisBench repository. Starting download and conversion from source.

which then results in an Error.

I used to download both datasets a lot in the past, without errors. Did something change in the meantime? Do I have to download them from the original source now?

**Comment by MarcoEsposito890** [comment]
Hi, thanks! I had downloaded them on Colab and not on my local pc! I'll just wait and see if it works later on or in the following days.

**Comment by yetinam** [comment]
Quick updated: the issue still persists and I unfortunately can not give an estimate yet when it will be solved. In the meantime, if you need the model weights, you can follow the workaround here: https://github.com/seisbench/seisbench/issues/206#issuecomment-1591002290

For the datasets, due to their size, I unfortunately can't provide a mirror right now. We're working on increasing the stability of our backend in the mid-term.

**Comment by yetinam** [comment]
Things should be back to normal now. Please reopen the issue if problems persist.
