### ISSUE TITLE
Deep Learning Experiments Logging [Enhancement]

### ISSUE THREAD

**Issue by geliAI** [seisbench/seisbench#232]
It would be useful to add an experiment logger. 
For example,
1. mlflow https://mlflow.org/docs/latest/tracking.html 
2. weight and biases https://wandb.ai/site
This is can facilitate experiments tracking/versioning etc.

**Comment by yetinam** [comment]
Hi @geliAI ,

thanks for the suggestion. I'm not sure if the suggestion really fits with the repository. SeisBench itself contains no code for model training where these loggers are commonly used. However, it is clearly intended to use SeisBench to build ML pipelines, as we've done it for example in the benchmark. Maybe it would be a good addition to the [benchmark repository](https://github.com/seisbench/pick-benchmark)? Please note that the benchmark repository is maintained substantially less actively than the main SeisBench repositor.

Closing this issue here but feel free to reopen if I misunderstood your intend or to open a similar issue in the benchmark repository.
