### ISSUE TITLE
Downloading Data

### ISSUE THREAD

**Issue by GeoJAC22** [seisbench/seisbench#238]
I am trying to download the metadata and hdf5 files for some IRIS data. I am very new to this all, and I have gone through the examples. I see we can download from seisbench using things like: 

`data = sbd.DummyDataset()`

or 

```
data = sbd.GEOFON(sampling_rate=100)
train, dev, test = data.train_dev_test()
```

But I am trying to get the files from IRIS, and the walk-throughs provided seem to only show me how to download from datasets within seisbench. I can access the IRIS data using `from obspy.clients.fdsn import Client` and then `client = Client("IRIS", timeout=10)` but I have not been able to figure out how to download the metadata and hdf5 files directly to my machine. 

I feel like this is probably a super simple issue that I just am missing somewhere since I can't seem to find any others having this problem, haha!

Any help would be appreciated!

**Comment by yetinam** [comment]
Hi @GeoJAC22 ,

thanks for your interest in SeisBench. Unfortunately, the question is not that simple. You're issue arises from different data formats. One one hand, the SeisBench format (CSV and hdf5), a format for short waveform snippets with metadata. On the other hand, the continuos, raw waveforms as available from IRIS through FDSN. SeisBench only offers data in SeisBench format, IRIS does not offer data in this format. In short, you can't download this data from IRIS, because it needs to be specifically prepared.

For you, there are two options. First, you can use the datasets already available in SeisBench. Second, you can compile your own dataset, for example based on the data from IRIS. Have a look at the tutorial notebook on creating a dataset for details.

I hope this answers your question.

**Comment by GeoJAC22** [comment]
Thank you! My brain wasn't making that connection I guess, so I appreciate that information. Also, that tutorial notebook for creating a dataset has exactly what I was looking for in that! Perfect. Thanks so much.
