### ISSUE TITLE
magnitude=999

### ISSUE THREAD

**Issue by Dong6Jx** [seisbench/seisbench#255]
Hi,
When I use GaMMA for phase correlation, why are the output magnitudes all "999"? Is it because config["use_amplitude"]=False?
If so, I would like to make config["use_amplitude"]=True so that the magnitude can be output correctly instead of "999", but there is no amplitude value output in the output of seisbench.model's classify() method. what should I do?

**Comment by yetinam** [comment]
Hi @Dong6Jx ,

indeed, GaMMA reports 999 if no amplitude values are provided. SeisBench does not extract amplitudes because it does not have knowledge of the instrument response. If you want to use amplitude information, you will need to extract it from the streams. See the [documentation of GaMMA](https://github.com/AI4EPS/GaMMA) for details on how to use amplitudes in association.
