### ISSUE TITLE
P- and S-picks probability depend on start time

### ISSUE THREAD

**Issue by Cthuulhaa** [seisbench/seisbench#261]
Hi, I have been testing the annotate method to obtain the time-dependent probability functions for P- and S-waves for a local quarry blast recorded at a German network in a 60 second time window (it is mostly a copy-paste of the example "applied picking"). I have noticed that the probability functions strongly vary with the start time parameter, even if few seconds are added or subtracted. This parameters affect so much the obtained probability functions, that in some situations some picks are not detected at all, or a P is mistaken to be a S-pick. Is this behaviour expected?

Cheers!

**Comment by yetinam** [comment]
Hi @Cthuulhaa ,
this is expected, even though very unfortunate behaviour. For a larger analysis, have a look at this PR #99 or [this paper](https://doi.org/10.1785/0220230003). In essence, the effect happens because the traces are chunked into windows for prediction, the windows are processed individually, and then the predictions are merged. To mitigate this issue, I'd recommend increasing the `overlap` parameter passed to `annotate`/`classify`. However, this will increase runtime. In addition, some models and training datasets show better translation invariance than others. For example, I've personally made good experiences with PhaseNet and with models trained on INSTANCE.
