### ISSUE TITLE
DeepDenoiser: Use torch for stft

### ISSUE THREAD

**Issue by miili** [seisbench/seisbench#269]
The bottleneck in the DeepDenoiser module is the short time Fourier transform.
Can `scipy.signal.stft` be replace with `torch.stft` to profit from GPU?

https://pytorch.org/docs/stable/generated/torch.stft.html

The method args differ from SciPy and are not that feature-rich. But are there any roadblocks?

**Comment by yetinam** [comment]
Hi @miili ,

there's a bit of a roadblock in the architecture of SeisBench. The way the `annotate` function works internally currently is:
```
- cut to windows
- preprocess each window individually
- stack to batches
- move from numpy to torch (and potentially to GPU)
- apply NN
- move back to numpy
- disassemble batches
- postprocess each window individually
```

Now clearly the better choice would be:
```
- cut to windows
- stack to batches
- move from numpy to torch (and potentially to GPU)
- preprocess windows in batch
- apply NN
- postprocess windows in batch
- move back to numpy
- disassemble batches
```
The second strategy is better, because it would allow to run pre- and postprocessing on GPU and because it could make use of vectorization.

In principle, it is possible to switch to the second model. However, this requires a bunch of changes:
- update the base class with the new structure (in both the async and process implementation, even though I feel it's probably fine to deprecate the latter anyhow)
- rewrite the pre- and postprocess functions of each model from numpy to pytorch and make sure the output stays unchanged
- update a collection of unit tests

This change should not only speed up DeepDenoiser but all other models as well. However, I currently don't have the capacity for it myself.
