### ISSUE TITLE
Question: is asyncio version of annotate/classify better?

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#272]
The documentation recommends using the asyncio interface (https://seisbench.readthedocs.io/en/stable/pages/models.html#speeding-up-model-application). The asyncio version is also the default option (`parallelism=None`). Intuitively, using multiprocessing should be better, but why is the asyncio interface recommended? In addition, when the model is run on a GPU, the parallelization is conducted on GPU, then which part of the processing workflow will be parallelized if I let the `parallelism` argument be a positive number?

**Comment by yetinam** [comment]
Hi @zhong-yy ,
thanks for the question. Indeed, the asyncio version will be faster in almost all cases. To answer the question what is actually parallelised when setting `parallelism`, it's the different preprocessing and postprocessing steps. In the asyncio version they will all run sequentially and not in parallel. Now why is multiprocessing still not faster? The problem is that the overhead for multiprocessing in python is huge and every task is pretty small. It's a pity and I'm sure that in principle there is still potential for further speed-ups.

**Comment by zhong-yy** [comment]
Thank you for your answer!
