### ISSUE TITLE
Issue with PyOcto: Empty DataFrames Returned During Association Process

### ISSUE THREAD

**Issue by jtaxo** [seisbench/seisbench#287]
Hi,

I am reaching out to you regarding an issue I encountered while using the PyOcto tool for seismic data analysis. Specifically, I am currently working on the association part of the process.

Despite the seismic stations detecting and recording the event accurately, I have encountered an issue when executing the following syntax: events, assignments = associator.associate_seisbench(picks, stations)

Upon reaching this part of the code, the associate_seisbench() function returns empty dataframes. I have reviewed my code and data inputs thoroughly, but I am unable to determine the root cause of this problem.

I have attached the seismic data files (mseed and xml) that I used for testing purposes. Please let me know if you require any additional information or if there are specific steps I should take to further diagnose the issue.

Best regards,
João

[sismo-vn.zip](https://github.com/seisbench/seisbench/files/15041934/sismo-vn.zip)

**Comment by yetinam** [comment]
Hi @jtaxo,

thanks for your interest in PyOcto. Empty outputs can have many reasons, usually related to the configuration of the associator and the input picks. What I would recommend you to do:

- Check that there are sufficient picks in the input. Maybe you can even find picks belonging to an event there?
- Check that the station input looks reasonable. Are there stations missing?
- Validate that the velocity model is appropriate.
- Increase the tolerance values and lower the number of required picks.

I hope this helps! I'm closing this issue here, but feel free to open a new issue if your problem persists. However, I'd ask you to open the issue on the [PyOcto repository](https://github.com/yetinam/pyocto/issues).
