### ISSUE TITLE
A few issues with MultiWaveformDataset

### ISSUE THREAD

**Issue by Pengling2022** [seisbench/seisbench#291]
Hello，yetinam:
I found a bug when I was studying the training of multiple data sets. I don’t know if I misunderstood it.
`waveform1` comes from the 10th waveform of `datasets[0]`, and `waveform2` is also the 10th waveform from `datasets[0]`. They are exactly the same.
In the same way, `waveform3` comes from the 10th waveform of `datasets[1]`, and `waveform4` also comes from the 10th waveform of `datasets[1]`, but I found that `waveform4` does not seem to get `datasets[1] `, but the 110th waveform of `datasets[0]` (such as `waveform5`).
![image](https://github.com/seisbench/seisbench/assets/96044614/8de2616d-27c4-4e49-ab8a-8249e8efea66)
![image](https://github.com/seisbench/seisbench/assets/96044614/e52e13ff-54d9-4d23-bf8b-e1780a38fae7)

Thanks！

**Comment by yetinam** [comment]
Hi @Pengling2022 ,
thanks for the report. I'm not sure if I understand the problem here. This seems to be intended behaviour. If you join two datasets A and B, the indexing in the dataset will work as follows:

- index 0 to len(A) - 1 refer to the first dataset
- index len(A) to len(B) - 1 refer to dataset two

In your example, waveform 110 in the combined dataset should therefore be example 110 from datasets[0], as you report. Only if datasets[0] would have exactly 100 samples, this should be example 10 from datasets[2].

I hope this clears up the confusion. Feel free to reopen the issue if you have further questions.
