### ISSUE TITLE
A volcanic earthquake dataset

### ISSUE THREAD

**Issue by zhong-yy** [seisbench/seisbench#303]
Hi @yetinam ,

As a follow-up to issue https://github.com/seisbench/seisbench/issues/297, we choose to make the waveforms public except those from Japan NIED. The waveform dataset now can be downloaded from [OneDrive](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155187577_link_cuhk_edu_hk/ERDz2m9BsE5PiK81hH3wQeQBzmw7SQj8GlN2591nQ2sPpQ?e=C5Uji0). The files are about 47G after unzipped. 

The dataset is divided into chunks according to the earthquake types and the regions: 
- Files whose names end with `_lp` are long-period earthquakes, `noise` noise waveforms, `rg` or `vt` regular local tectonic earthquakes.
- Files containing `ak` are waveforms from Alaska, `hw` for Hawaii, `ncedc` for Northern California, `cascade` for Cascade volcanoes.

**Comment by yetinam** [comment]
Hi @zhong-yy,

thanks for this contribution. I think this is a great addition to SeisBench. For the next steps, I'd suggest that I'll have a look at the data to see if any minor adjustments are necessary. Then I'll upload the files to our SeisBench repository. At the same time, could you write a PR for adding the datasets. It's pretty easy, because you essentially just create empty classes and the inherited functionality takes care of the rest. See #292 as an example.

**Comment by zhong-yy** [comment]
Thanks for the instruction! I have written a PR.  Please let me know if any change is necessary.
