### ISSUE TITLE
Considerations for scaling seisbench annotation examples to larger datasets

### ISSUE THREAD

**Issue by scottyhq** [seisbench/seisbench#64]
Thanks for this fantastic library! @zoekrauss and I are working on scaling some of the existing Colab examples to work with relatively large datasets (multiyear 100+ station networks). In particular we'd like to document recommendations for taking advantage of computational resources with `model.annotate()`, which currently uses `asyncio` for concurrency (https://github.com/seisbench/seisbench/pull/51). 

We have more familiarity with libraries like `concurrent.futures` and `dask` that use processes or threads, but are unsure how to combine these together effectively - for example, distributing `model.annotate()` on a multicore machine (e.g. running on https://aws.amazon.com/sagemaker/studio-lab/ or https://planetarycomputer.microsoft.com/docs/overview/environment/): If not using Colab, what sort of machines and workflow do you recommend? for example, don't bother with multi-core machines? use a faster GPU? etc.

This came up for us when naively trying to use multithreading to speed up `model.annotate()`, and encountering the following error (pseudocode and abbreviated traceback below for brevity):
```python
# this machine has vCPU=4.0, what if we break up 400 traces into 4 groups of 100 traces?...
import dask
batch_size = 100
batched_list = [big_stream[i:i + batch_size] for i in range(0, len(big_stream), batch_size)]

streams = batched_list[:4]
streams[0]
#100 Trace(s) in Stream:
#CX.0000..HHZ | 2007-01-02T05:47:09.998392Z - 2007-01-02T05:50:29.998392Z | 100.0 Hz, 20001 samples
#...
#(98 other traces)
#...
#CX.0099..HHZ | 2007-01-02T05:47:09.998392Z - 2007-01-02T05:50:29.998392Z | 100.0 Hz, 20001 samples
# 

@dask.delayed
def denoise(stream):
    return model.annotate(stream)

lazy_denoise = [denoise(stream) for stream in streams]
dask.compute(*lazy_denoise, scheduler='threads')
```
```pytb
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```
Switching to scheduler='processes' does not raise an error but is slower than scheduler='single-threaded'. Not sure if this is an issue specific to dask, or some incompatibility with the code using `nest_asyncio` to set up event loops...
https://github.com/seisbench/seisbench/blob/f704e2954188349ccf244c4763b07e2d86de74c3/seisbench/models/base.py#L366-L370

We'd be happy to add a pull request with additional documentation, but thought discussing in an issue first would help get clarity on the current implementation.

**Comment by yetinam** [comment]
Hi @scottyhq, hi @zoekrauss,
thanks for raising this point! I think it's a very interesting question how to apply the models to large-scale datasets. For upscaling the models, it is essential to identify the bottleneck(s). Some possibilities are:

- data IO from disk (won't matter if the data is already in memory)
- CPU for pre- and postprocessing
- memory bus capacity to GPU
- GPU load

If the limitation is data IO, there's nothing that can be done except changing the underlying hardware and potentially the access patterns. For the CPU limited case, there is actually something that could be changed inside SeisBench. So far, each pre- and postprocessing step is not parallelized in itself. So in case the CPU is not busy on all cores (i.e., if the job is not actually saturating the CPU) there is something to gain. I could increase the possiblem parallelization and I assume it's probably worthwhile doing this anyhow. If the memory bus of the GPU is saturated, there is again nothing that can be done, except changing to hardware with a larger memory bus. However, I'd assume this is not the bottleneck, because the bus should handle > 1GB per second without any issues. More or less holds for the GPU load. If the GPU is at maximum capacity, then there's not really a chance to get more out of it without optimizing the actual deep learning models somehow. Do you maybe have a chance to check the resources and see if you can identify the bottleneck?

Now to the question on how to parallelize: in general, I think it is advisable to only have one instance of the neural network model on the GPU. Having it multiple times on the GPU would simply waste GPU memory, but shouldn't really lead to any speed-up if the model is properly served by the CPU. For optimal utilization of the GPU, I'd recommend to set the batch size as large as possible given the existing GPU memory. Consequently, as long as only a single machine is used, I think parallelization should be implemented within SeisBench instead of using wrappers around it. I'd be happy to work on these modifications in the next days (it should hopefully not take too long) once we identified a suitable strategy. When parallelising across multiple machines, it might be possible to use the embarassingly parallel nature of the task, i.e., simply divide by stations, time intervals, or boths. What do you think about the strategy? Would you maybe be able to benchmark potential modifications on your use case to see if it's actually possible to achieve a speed-up this way?

Regarding the `RuntimeError`, I'm not quite sure where it originates from. Could you post the full trace so I can see which line in the code throws the error? To check whether indeed `nest_asyncio` is responsible for the error, you could try installing a [developer version](https://github.com/seisbench/seisbench/blob/main/CONTRIBUTING.md#installing-seisbench-for-development-purposes) and then comment out the `nest_asyncio` command (for running from the console) or replace it with `asyncio.get_event_loop` (for running in ipython/jupyter). For doing this in colab, you'll probably have to download the repository to google drive and mount it from there. `nest_asyncio` is necessary to run within both the command line and ipython/jupyter instances, as they automatically have an event loop running.

**Comment by yetinam** [comment]
Hi @scottyhq, hi @zoekrauss,
we've now implemented a parallel interface. It's not yet available through pypi, but it's in the `main` branch, so you can install it with `pip install git+https://github.com/seisbench/seisbench.git` even on colab. Feel free to reach out if you have further questions/suggestion/...
